### ISSUE TITLE
Invite by email needs tailored link

### ISSUE THREAD

**Issue by simonhrjohnson** [isTravis/fiftynifty#101]
Invite by email generates this text in part

"This tool, http://fiftynifty.org, was created by Andy Lippman and colleagues at the MIT Media Lab, and it will help you speed dial your representatives and alert your friends."

But if people click on that link, we don't know who invited them -- and this may be causing some network deterioration

Can we make that embedded link be tailored to the person issuing the invitation (such a tailored link does appear at the end of the generated email)

**Comment by isTravis** [comment]
Done by @jasrub
