### ISSUE TITLE
make it easier to logout

### ISSUE THREAD

**Issue by simonhrjohnson** [isTravis/fiftynifty#107]
I want to logout from FiftyNifty, so that I can check what https://www.fiftynifty.org/?ref=3 (the link I send) looks like to people who receive it (i.e., other than me when I am logged in)

There should be a logout button on the front page (I think there was but I don't see it now).

**Comment by lemeb** [comment]
We can make the design of the logout button more visible...

The logout button on the front page is already included in pull request #105

**Comment by jasrub** [comment]
Currently the is a logout button in your profile page.
It's red and somewhat hidden under the red representatives box.

I think we need to ask if we really want to make the logout button more visible. users may click it by accident (clicking whatever is clickable) and then will have to go through the (annoying?) process of verifying their phone number again.

we initially decided is should not be simple to logout.
Do you think it should be? 
maybe adding a popup of "are you sure you ant to log out?" is an option if we put the logout button in the landing page?

**Comment by simonhrjohnson** [comment]
Jasmin

Good points.  I just went through the process and I agree – let’s not make it too easy to logout.  Leaving the button where it is should be fine

Also, I like the fact that if you logout, you need a new authorization code in order to get back in.  This makes us seem concerned about security and integrity of identities (which is true)

Thanks
Simon

**Comment by lemeb** [comment]
Well, making sure that people don't click on logout by accident and actively making the logout button hard to find are two different things. Probably what we would need is to make the logout button more visible but ask to confirm. 

To kind of hide the logout button because we don't want to click on it by accident is really detrimental to people who *actually* want to log out.

**Comment by jasrub** [comment]
When will a user want to logout? 
(unless it's is one of us testing all functionalities).

I really think this functionality needs to be hidden. 
How about adding a small logout option at the footer - if you really insist this should be on every page?

**Comment by lemeb** [comment]
The small logout option at the footer is a very good idea

**Comment by ABLippman** [comment]
Logging out removes the cookie.  There is no good reason for anyone but us ringers to log out.  Let’s don’t make it more evident.  THere is little value in it.

andy



Begin forwarded message:
