### ISSUE TITLE
text in How to Call

### ISSUE THREAD

**Issue by simonhrjohnson** [isTravis/fiftynifty#108]
"I’d like so-and-so to take a strong position demanding a hearing on Russian Influence on our elections and government. I want to know whether there is more involved." 

This would be better as:
"I’d like [insert the name of your Representative or Senator here] to take a strong position demanding a full congressional investigation into the influence of Russia in our electoral process and on the Trump administration.  I want to know whether there is more involved than has already been made public.   I am very concerned about this issue."

**Comment by ABLippman** [comment]
What do you think about toning down the message and returning to the option of more than one issue?

andy

**Comment by simonhrjohnson** [comment]
I think the front page should say "Issues of the day," and list several.  We can update within each theme daily if needed

But we really need a "create your own" option

Could each of those have their own suggested script associated?

On Feb 19, 2017, at 8:55 AM, ABLippman <notifications@github.com<mailto:notifications@github.com>> wrote:

What do you think about toning down the message and returning to the option of more than one issue?

andy

**Comment by isTravis** [comment]
Done by @scherna
