### ISSUE TITLE
sign up problem reported

### ISSUE THREAD

**Issue by simonhrjohnson** [isTravis/fiftynifty#110]
Potential user, on iPhone (202-550-5174) tried to sign up this afternoon, but verification codes did not work around 4:30-5pm.  He tried both text and voice verification procedures.

**Comment by lemeb** [comment]
Hm. I don't see anything in the database.

**Comment by simonhrjohnson** [comment]
I just talked to this potential user again.  He is using an iPhone 6s, so this may be a Safari issue (in some version).  When he puts in the verification code, the system circles endlessly, i.e., tries to load but does not get anywhere.

He tried to do this with both the code sent by text and by phone/calling.  He had the same problem both ways.

**Comment by simonhrjohnson** [comment]
The same person is now signed up, but reported difficulties using Chrome on a PC...

**Comment by ABLippman** [comment]
TRy a refresh…

andy

**Comment by simonhrjohnson** [comment]
Can we add a user-friendly instruction on what to do if the system hangs up during registration?

E.g. First try refresh, the close and restart browser, etc

On Feb 20, 2017, at 7:37 AM, ABLippman <notifications@github.com<mailto:notifications@github.com>> wrote:

TRy a refresh…

andy

**Comment by ABLippman** [comment]
I'll look at the text today.  Simplify, simplify, simplify.

And more embracing

Andy

Sent in haste from my pad...

**Comment by isTravis** [comment]
Same as #113
