### ISSUE TITLE
Spanish version possible?

### ISSUE THREAD

**Issue by simonhrjohnson** [isTravis/fiftynifty#111]
Could some part of the website be in Spanish, e.g., a version of the front page and some of the About material?  This request comes from a potential user with network connections who are more comfortable in Spanish.

**Comment by isTravis** [comment]
This is a pretty significant architecture change - and given the rate at which we're updating the text, I think we should table this idea until the platform is more stable.

**Comment by simonhrjohnson** [comment]
No problem – just leave it on the potential list. Thanks, Simon
