### ISSUE TITLE
Could there be a second leaderboard, by points

### ISSUE THREAD

**Issue by simonhrjohnson** [isTravis/fiftynifty#112]
The leaderboard is by number of states, presumably with points as a tie breaker

Can we have a second leaderboard -- or a second way to show the same data -- by points?  So users could choose which leaderboard to look at

This would encourage people to make more calls early on -- get your points on the board.  Building states takes longer.

One new user suggested this -- with the idea of encouraging people to get going and build some momentum

**Comment by jasrub** [comment]
We can now sort leaderboard by points, states, or number of friends who joined
