### ISSUE TITLE
Leaderboard Tools

### ISSUE THREAD

**Issue by jasrub** [isTravis/fiftynifty#144]
We should have tools in the leaderboard to present:

- Users sorted by states count (current presentation)
- Users sorted by points
- Users sorted by number of friends they invited (even if no calls made, for example this user - https://www.fiftynifty.org/268 invited a lot of friends, but we don't see it in the leaderboard because non of the friends made calls)
- Showing the user's personal status in the leaderboard - where am I ranked?

**Comment by scherna** [comment]
I wrote a few helper functions to get the leaders sorted in different ways, but still need to add buttons to change the sort
