### ISSUE TITLE
Add A/B testing

### ISSUE THREAD

**Issue by jasrub** [isTravis/fiftynifty#24]
Have 2 different texts in the Landing page, randomly show them to new users and save to database which one was show.
If a user is logged -in make sure we always show the text that she saw first.

Our President’s Executive order halting some legal immigrants has created a lot of discussion both from people who are for and those against the order. We want to call Congresspeople throughout the country to tell them our opinion. Real phone call matter, so we are starting the Fifty Nifty challenge to see if you can use your network to get 50 people in 50 states to make a call. The network that gets the most calls wins, but we all win when we call for an effective democracy. Read on to see how to win and hints about what to say.

Alternate Entry
Real phone calls from real constituents matter to elected officials.  The FiftyNifty Challenge is your chance to build a grassroots social network for action.  Your goal is to get 50 people in 50 states to directly tell their congresspeople what they think.  The networks that makes the most calls wins and we all win when we call for an effective democracy.  It’s a challenge for you and your friends, and a chance to watch the growth of your network.  You can call about any issue of importance to you.  Read on to see how to win and hints about what to say.

**Comment by isTravis** [comment]
Given this a bit of thought technically. I think we should make room for other AB tests as we go. We can assign a simple [1-100] number to the user model titled `userType`. For the splash screen, we can say `>50` sees one text, and `<50` sees another. 

This gives us space for future A/B tests, such that we could have four groups of users see four different buttons (<25, 25-50, 50-75, >75). 

The users `userType` number is grabbed from the localStorage if logged in, or randomly generated and passed up with the SignUp if not logged in.

**Comment by ABLippman** [comment]
Should I clear past logins and try again?

**Comment by ABLippman** [comment]
I just started it on the iPad and learn more has the old text.

**Comment by ABLippman** [comment]
I'm having response troubles.  On the iPhone, I have the option of Your Profile or leaderboard.  The profile turns red but does nothing.  I want to log out and start from zero.  On the iPad, I get the login response.  On the Android, I get nothing more than a white screen...

**Comment by jasrub** [comment]
@ABLippman I added a new issue - #29 to track the problem on different devices, let's continue this talk there

**Comment by ABLippman** [comment]
To preserve the 50/50 test nature, the learn more page should be programmed to put the issue at the top for those who get the issue version, and at the bottom for the game version
