### ISSUE TITLE
Validate the website on different devices

### ISSUE THREAD

**Issue by jasrub** [isTravis/fiftynifty#29]
We should validate that all functionality work an different devices

**Comment by jasrub** [comment]
@ABLippman - Can you bring iPhone Ipad and Android to lab tomorrow so we can figure out what is not working where?

**Comment by ABLippman** [comment]
I'll bring them.  iPad looks good.  What do you think we should do about the login validation.  I don't think I can get a standard text on the iPad...  And since we removed the call-in number, you are pretty much locked into running this on a phone.  Do you thinnk that is OK?

**Comment by jasrub** [comment]
You sign up with your phone number (you can do both cell-phone or landline)  and access the website from any device (smartphone, desktop, or tablet). When you click call, we call the number you signed up with, not the device you are using.

We will also add an option of "call me with the verification code" in the login page (tracked on #30 ) so you can sign up with a landline and still login and logout without needing to receive text messages

**Comment by ABLippman** [comment]
That’s brilliant!

Also, didn’t we modify the call button to warn you that you would be called back — answer the phone

andy
