### ISSUE TITLE
Visualize general network data - global count

### ISSUE THREAD

**Issue by jasrub** [isTravis/fiftynifty#86]
How many calls were made
How many calls in each state

Also, at some stage can we differentiate between senators and reps, to show who we have and have not reached?  This would be really valuable to know and to visualize

**Comment by ABLippman** [comment]
Folks, we need to be able to access the global map by thursday at the latest.  It's really needed in order to see what's going on so as to explain the app to people we meet.  The leaderboard is not enough.  

andy

**Comment by jasrub** [comment]
Growth
number of states
number of users
number of calls
calls length
