### ISSUE TITLE
claiming network connections

### ISSUE THREAD

**Issue by simonhrjohnson** [isTravis/fiftynifty#98]
An active user asks: "So, if I email invitations to join fifty nifty outside of the website, I don’t build my network?  Maybe there’s a way to ask “how’d you hear of us” or something like that?"

If we want people to feel good about building and maintaining their networks, we should give them an option like this -- or an ability to claim people as children (presumably subject to confirmation from that person?)

**Comment by ABLippman** [comment]
You clip your invite.  We can’t be psychic about this.

andy



Begin forwarded message:

**Comment by isTravis** [comment]
This is a bit tedious and painful to implement as a default solution. I'd be fine having some text saying, 'Email us if a link should be made'

**Comment by simonhrjohnson** [comment]
Good idea, if you don’t mind getting emails like that
